ProductsApi/Models/CommandResult.cs
namespace ProductsApi.Models
{
    public class CommandResult
    {
        public bool Success { get; set; }
        public string Message { get; set; }
    }
}

ProductsApi/Models/Dto/DeleteProductDto.cs
namespace ProductsApi.Models.Dto
{
    public class DeleteProductDto
    {
        public int Id { get; set; }
    }
}

ProductsApi/Models/Dto/DeleteStorageDto.cs
namespace ProductsApi.Models.Dto
{
    public class DeleteStorageDto
    {
        public int Id { get; set; }
    }
}

ProductsApi/Models/Dto/ListProducts.cs
namespace ProductsApi.Models.Dto
{
    public class ListProducts
    {
        public List<StorageModel> Products { get; set; }
    }
}

ProductsApi/Models/Dto/NewProductDto.cs
namespace ProductsApi.Models.Dto
{
    public class NewProductDto
    {
        public int StorageId { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public float Weight { get; set; }
        public int Count { get; set; }
    }
}

ProductsApi/Models/Dto/NewStorageDto.cs
namespace ProductsApi.Models.Dto
{
    public class NewStorageDto
    {
        public string Name { get; set; }
    }
}

ProductsApi/Models/NewProductDto.cs
namespace ProductsApi.Models
{
    public class NewProductDto
    {
        public string StorageName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public float Weight { get; set; }
        public int Count { get; set; }
    }
}

ProductsApi/Models/NewStorageDto.cs
namespace ProductsApi.Models
{
    public class NewStorageDto
    {
        public string Name { get; set; }
    }
}

ProductsApi/Models/Product.cs
namespace ProductsApi.Models
{
    public class Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public float Weight { get; set; }
        public int Count { get; set; }
        public Product(string? name, string? description, int count, float weight)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                throw new ArgumentNullException(nameof(name));
            }

            if (string.IsNullOrWhiteSpace(description)) 
            {
                throw new ArgumentNullException(nameof(description));
            }

            if (weight <= 0f)
            {
                throw new ArgumentOutOfRangeException(nameof(weight));
            }

            if (count < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(count));
            }

            Id = Guid.NewGuid().ToString();
            Name = name;
            Description = description;
            Weight = weight;
            Count = count;
        }
        public override string ToString()
        {
            return $"[Name = {Name}, Description = {Description}, Weight = {Weight}, Count = {Count}]";
        }
    }
}

ProductsApi/Models/ProductModel.cs
namespace ProductsApi.Models
{
    public class ProductModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public float Weight { get; set; }

        public int Count { get; set; }

        public StorageModel Storage { get; set; }

        public override string ToString()
        {
            return $"[Name = {Name}, Description = {Description}, Weight = {Weight}, Count = {Count}]";
        }
    }
}

ProductsApi/Models/Storage.cs
using ProductsApi.Models;

namespace ProductsApi.Models
{
    public class Storage
    {
        public string Name { get; set; }
        public List<Product> Products { get; set; }
    }
}

ProductsApi/Models/StorageModel.cs
namespace ProductsApi.Models
{
    public class StorageModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<ProductModel> Products { get; set; }

    }
}

ProductsApi/Controllers/StoragesController.cs
using Microsoft.AspNetCore.Mvc;
using ProductsApi.Models;
using ProductsApi.Models.Dto;
using ProductsApi.Services;
using ProductsApi.Views.Home;

namespace ProductsApi.Controllers
{
    public class StoragesController : Controller
    {
        private readonly IStoragesService _service;

        public StoragesController(IStoragesService service)
        {
            _service = service;
        }

        public IActionResult GetAllProducts()
        {
            return View("ListProducts", _service.GetAllProducts());
        }

        public IActionResult GetAllStorages()
        {
            return View("ListStorages", _service.GetAllStorages());
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct([FromForm] NewProductDto newProduct)
        {
            await _service.AddProductAsync(newProduct);
            return RedirectToAction("GetAllStorages");
        }

        [HttpPost]
        public async Task<IActionResult> AddStorage([FromForm] NewStorageDto newStorage)
        {
            await _service.AddStorageAsync(newStorage);
            return RedirectToAction("GetAllStorages");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct([FromForm] DeleteProductDto deleteProduct)
        {
            await _service.DeleteProductAsync(deleteProduct);
            return RedirectToAction("GetAllStorages");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteStorage([FromForm] DeleteStorageDto deleteStorage)
        {
            await _service.DeleteStorageAsync(deleteStorage);
            return RedirectToAction("GetAllStorages");
        }

        public IActionResult TotalWeight()
        {
            return RedirectToAction("GetAllProducts");
        }
    }
}

ProductsApi/Views/Storages/ListProducts.cshtml
@using ProductsApi.Models;
@model List<ProductModel>
@{
    <h1>Products</h1>
    <div>
        @foreach (var product in Model)
        {
            <div>
                <h1>@product.Name</h1>
                <h2>@product.Description</h2>
                <p>Count: @product.Count  Weight: @product.Weight Storage: @product.Storage.Name</p>
            </div>
        }
    </div>
}

ProductsApi/Views/Storages/ListStorages.cshtml
@using ProductsApi.Models;
@model List<StorageModel>


@{
    foreach (var storage in Model)
    {
        <div>
            <h1>@storage.Name</h1>
            @using (Html.BeginForm("DeleteStorage", "Storages", FormMethod.Post))
            {
                <input type="hidden" name="Id" value="@storage.Id" />
                <div>
                    <input type="submit" value="delete storage" />
                </div>
            }

            @{
                if (storage.Products != null)
                {
                    foreach (var product in storage.Products)
                    {
                        <h3>@product.ToString()</h3>

                        @using (Html.BeginForm("DeleteProduct", "Storages", FormMethod.Post))
                        {
                            <input type="hidden" name="id" value="@product.Id" />
                            <div>
                                <input type="submit" value="delete product" />
                            </div>
                        }
                    }
                }
            }

            <h1>Add new product:</h1>
            @using (Html.BeginForm("AddProduct", "Storages", FormMethod.Post))
            {
                <input type="hidden" name="storageId" value="@storage.Id" />

                <div>
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="name" />
                </div>

                <div>
                    <label for="description">Description:</label>
                    <input type="text" id="description" name="description" />
                </div>

                <div>
                    <label for="weight">Weight:</label>
                    <input type="text" id="weight" name="weight" />
                </div>

                <div>
                    <label for="count">Count:</label>
                    <input type="text" id="count" name="count" />
                </div>

                <div>
                    <input type="submit" value="Add" />
                </div>
            }
            
        </div>
    }

    <h1>Add new storage:</h1>
    @using (Html.BeginForm("AddStorage", "Storages", FormMethod.Post))
    {
        <div>
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" />
        </div>

        <div>
            <input type="submit" value="Add" />
        </div>
    }
}

ProductsApi/Views/Storages/TotalWeight.cshtml
@page
@model decimal?
@{
    <div>
        <h1>Total Weight = "@Model"</h1>
    </div>
}